package org.coletivoJava.fw.projetos.SB_CRIADOR_COMPONENTE.api.model.beanexemplo;

import com.super_bits.Super_Bits.SB_CRIADOR_COMPONENTE.model.BeanExemplo;
import com.super_bits.modulosSB.SBCore.modulos.objetos.validador.InfoReferenciaEntidade;

@InfoReferenciaEntidade(tipoObjeto = BeanExemplo.class)
public enum CPBeanExemplo {
	_ID, _EMAIL, _SELETOROPCAO, _DESCRITIVO, _TELEFONE, _DATA, _CELULAR, _TELINTERNACIONAL, _CPF, _CNPJ, _CPTESTE, _INSCRICAOESTADUAL, _INSCRICAOMUNICIPAL, _COR, _MASCARAESPECIAL, _HTML, _SITE, _URL, _SENHA, _VALIDACAOLOGICAAPENASPAR, _VALIDACAOLOGICAAPENASGAULESES, _VALORLOGICOBEANALEATORIO, _LISTADINAMICAALEATORIA, _QUANTIDADE, _PORCENTAGEM, _DINHEIRO, _DATAALTERACAO, _APELIDO, _TEMPLATEHTML, _NOME, _LOGRADOURO, _COMPLEMENTO, _CEP, _DATAHORA, _ARQUIVO, _ARQUIVODECATEGORIA, _LOCALIZACAO, _BEANFILHO, _BAIRRO, _BEANSELECIONADODALISTADESCRITIVA, _BEANSELECIONADODALISTAFABRICA, _BENSELECIONADOLISTAPORCAMPO, _UNIDADEFEDERATIVA, _CIDADE, _LISTASEXEMPLO, _LISTADUASOPCOES, _LISTAUMAOPCAO, _LISTAOITOOPCOES, _LISTADEZOPCOES, _LISTAPARTICULAR, _VERDADEIROOUFALSO, _GRUPOCAMPOCOMPLETO, _GRUPOCAMPOSIMPLES, _ACAOGRUPOTESTE, _CAMPOVINCULADO1, _TEXTOLABELPADRAOTESTE, _OBJETOFABRICA, _CAMPOVINCULADO2, _CAMPOVINCULADO3, _QTDCAMPOVINCULADO1GETS, _QTDCAMPOVINCULADO1SETS, _QTDCAMPOVINCULADO2GETS, _QTDCAMPOVINCULADO2SETS, _QTDCAMPOVINCULADO3GETS, _QTDCAMPOVINCULADO3SETS;

	public static final String id = "id";
	public static final String email = "email";
	public static final String seletoropcao = "seletorOpcao";
	public static final String descritivo = "descritivo";
	public static final String telefone = "telefone";
	public static final String data = "data";
	public static final String celular = "celular";
	public static final String telinternacional = "telInternacional";
	public static final String cpf = "cpf";
	public static final String cnpj = "cnpj";
	public static final String cpteste = "cpTeste";
	public static final String inscricaoestadual = "inscricaoEstadual";
	public static final String inscricaomunicipal = "inscricaoMunicipal";
	public static final String cor = "cor";
	public static final String mascaraespecial = "mascaraEspecial";
	public static final String html = "html";
	public static final String site = "site";
	public static final String url = "url";
	public static final String senha = "senha";
	public static final String validacaologicaapenaspar = "validacaoLogicaApenasPar";
	public static final String validacaologicaapenasgauleses = "validacaoLogicaApenasGauleses";
	public static final String valorlogicobeanaleatorio = "valorLogicoBeanAleatorio";
	public static final String listadinamicaaleatoria = "listaDinamicaAleatoria";
	public static final String quantidade = "quantidade";
	public static final String porcentagem = "porcentagem";
	public static final String dinheiro = "dinheiro";
	public static final String dataalteracao = "dataAlteracao";
	public static final String apelido = "apelido";
	public static final String templatehtml = "templateHtml";
	public static final String nome = "nome";
	public static final String logradouro = "logradouro";
	public static final String complemento = "complemento";
	public static final String cep = "cep";
	public static final String datahora = "dataHora";
	public static final String arquivo = "arquivo";
	public static final String arquivodecategoria = "arquivoDeCategoria";
	public static final String localizacao = "localizacao";
	public static final String beanfilho = "beanFilho";
	public static final String bairro = "bairro";
	public static final String beanselecionadodalistadescritiva = "beanSelecionadoDaListaDescritiva";
	public static final String beanselecionadodalistafabrica = "beanSelecionadoDaListaFabrica";
	public static final String benselecionadolistaporcampo = "benSelecionadoListaPorCampo";
	public static final String unidadefederativa = "unidadeFederativa";
	public static final String cidade = "cidade";
	public static final String listasexemplo = "listasExemplo";
	public static final String listaduasopcoes = "listaDuasOpcoes";
	public static final String listaumaopcao = "listaUmaOpcao";
	public static final String listaoitoopcoes = "listaOitoOpcoes";
	public static final String listadezopcoes = "listaDezOpcoes";
	public static final String listaparticular = "listaParticular";
	public static final String verdadeirooufalso = "verdadeiroOuFalso";
	public static final String grupocampocompleto = "grupoCampoCompleto";
	public static final String grupocamposimples = "grupoCampoSimples";
	public static final String acaogrupoteste = "acaoGrupoTeste";
	public static final String campovinculado1 = "campoVinculado1";
	public static final String textolabelpadraoteste = "textoLabelPadraoTeste";
	public static final String objetofabrica = "objetoFabrica";
	public static final String campovinculado2 = "campoVinculado2";
	public static final String campovinculado3 = "campoVinculado3";
	public static final String qtdcampovinculado1gets = "qtdCampoVinculado1gets";
	public static final String qtdcampovinculado1sets = "qtdCampoVinculado1sets";
	public static final String qtdcampovinculado2gets = "qtdCampoVinculado2gets";
	public static final String qtdcampovinculado2sets = "qtdCampoVinculado2sets";
	public static final String qtdcampovinculado3gets = "qtdCampoVinculado3gets";
	public static final String qtdcampovinculado3sets = "qtdCampoVinculado3sets";
}